---
# File: .github/workflows/repo-sync.yml
name: Sync Fork

on:
  schedule:
  - cron:  "0 17 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "ophub/amlogic-s9xxx-openwrt"
        source_branch: "*"
        destination_branch: "*"
        github_token: ${{ secrets.TOKEN }}
